/*
 * This Java source file was auto generated by running 'gradle buildSetup --type java-library'
 * by 'berinle' at '10/22/13 3:46 PM' with Gradle 1.8
 *
 * @author berinle, @date 10/22/13 3:46 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
